config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'items#index'
  get '/items/:id', to: 'items#show', as: 'item'
  # get '/ordered_items/:id', to: 'items#buy', as: 'buy'
  post '/items/:id', to: "carts#add_to_cart", as: :adding
  get :mon_panier, to: "carts#index", as: :mon_panier
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :added_items, through: :cart_items
end

app/models/item.rb
class Item < ApplicationRecord
    has_and_belongs_to_many :carts
    has_and_belongs_to_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_and_belongs_to_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :orders
  #has_many :purchased_items, through: :orders


  has_one :cart
  has_many :added_items, through: :cart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def add_to_cart
        set_item
        if @cart.added_items << @item
          flash.now[:success] = "Element ajouté à votre panier"
          redirect_to mon_panier_path
        end
    end
    def index
        @user = current_user
        @items = @user.added_items
        if Cart.where(user: @user)
            @total = calcul_total
        end
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
    end
    def show
        @item = Item.find(params[:id])
    end   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/cart/index.html.erb
<p> page index </p>

app/views/items/index.html.erb
<main role="main">
<div class="album py-5 bg-light">
<div class="container">

<h1>Voici nos chats</h1>
<% @items = Item.all %>
<% @items.each do |item| %>
    <%= item.title %><br/>
    <%= item.description %><br/>
    <%= item.price %><br/>
    <img src="<%= item.image_url %>", class: "img-responsive">
    <p class='button_list_table'>
    <%= link_to "Détails", item_path(item), class: "btn btn-success" %></p><br/><br/><br/>
<% end %>

</div>
</div>

</main>

app/views/items/show.html.erb
<p>
  <strong>His name : </strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price</strong>
  <%= @item.price %>
</p>

<% if user_signed_in? %>
  <p class='button_list_table'>
  <%= link_to "Ajouter au panier", mon_panier_path, class: "btn btn-success" %> </p><br/><br/><br/>
<% end %>`

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Panier</a>
     </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>
        <% if user_signed_in? %>
          <%= link_to "Nos chats", root_path %>
        <% end %>
      </ul>

        <ul class="nav navbar-nav navbar-right"style="margin-right:10px; margin-top:1.3%;">
          <% if user_signed_in? %>
            <%= link_to destroy_user_session_path, method: :delete do %><span class="glyphicon glyphicon-log-out"></span> Logout<%end%>
          <% else %>

          <li><%= link_to new_user_session_path do %><span class="glyphicon glyphicon-user"></span> Sign Up<%end%></li>
          <li><%= link_to new_user_registration_path do %><span class="glyphicon glyphicon-log-in"></span> Login<%end%></li>
  
          <% end %>
    </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MRTecomV1</title>
    <%= csrf_meta_tags %>

    <!-- Custom styles for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-freelancer/css/freelancer.min.css" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="https://blackrockdigital.github.io/startbootstrap-freelancer/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-freelancer/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>